---
galaxy_info:
  author: your name
  description: Install Helm CLI
  company: your company (optional)
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - focal
    - jammy
  galaxy_tags:
  - helm
dependencies: []