---
galaxy_info:
  author: An Pham
  description: Install Helm CLI on Ubuntu systems
  company: durianLAB.tech
  license: GPL-2.0-or-later
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - focal
    - jammy
  galaxy_tags:
  - helm
  - kubernetes
dependencies: []