---
- name: Create ansible user
  user:
    name: ansible
    state: present
    shell: /bin/bash
    create_home: yes
    groups: sudo
    append: yes

- name: Add ansible user to sudoers with NOPASSWD
  lineinfile:
    path: /etc/sudoers
    state: present
    line: 'ansible ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'