galaxy_info:
  author: An Pham
  description: Deploy NGINX Ingress Controller via Helm
  company: durianLAB.tech
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - kubernetes
    - helm
    - ingress
    - nginx
dependencies: []