galaxy_info:
  author: your_name
  description: Deploy NGINX Ingress Controller via Helm
  company: your_company

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - kubernetes
    - helm
    - ingress
    - nginx

dependencies: []