galaxy_info:
  author: An Pham
  description: Install and configure GitHub Actions self-hosted runner
  company: durianLAB.tech
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: GenericLinux
      versions:
        - all
  galaxy_tags:
    - github
    - actions
    - runner
    - ci
dependencies: []
