---
# roles/autofs_mounts/tasks/main.yml

- name: Install autofs
  apt:
    name: autofs
    state: present

- name: Create /etc/auto.master
  copy:
    content: |
      /mnt /etc/auto.mounts --timeout={{ autofs_timeout }}
    dest: /etc/auto.master
    owner: root
    group: root
    mode: '0644'
  notify: restart autofs

- name: Create /etc/auto.mounts
  template:
    src: auto.mounts.j2
    dest: /etc/auto.mounts
    owner: root
    group: root
    mode: '0644'
  notify: restart autofs

- name: Restart autofs service
  service:
    name: autofs
    state: restarted
  listen: "restart autofs"
